import { IProduct } from "@/type";

export const hitProducts: IProduct[] = [
	{
		id: 1,
		title: "Soatsiz Alisali Yandex Mini Stansiyasi aqlli karnayi, Kul rang",
		image: "/products/product-1.png",
		price: 1190000,
		monthlyPrice: 99167,
		monthlyDuration: 18,
		rating: 5,
		reviewsText: "Sharh yo‘q",
		badge: "Xit savdo",
		discount: "50•0•2",
	},
	{
		id: 2,
		title: "Haier H43K801UG Smart Televizori",
		image: "/products/product-2.png",
		price: 4800000,
		monthlyPrice: 400000,
		monthlyDuration: 18,
		reviewsText: "Sharh yo‘q",
		badge: "Xit savdo",
		discount: "0•0•12",
		discountSecondary: "50•0•2",
	},
	{
		id: 3,
		title: "Alisali Yandex Duo Max Stansiyasi aqlli karnayi, Qora, 60Vt",
		image: "/products/product-3.png",
		price: 6990000,
		monthlyPrice: 582500,
		monthlyDuration: 18,
		reviewsText: "Sharh yo‘q",
		badge: "Xit savdo",
		discount: "50•0•2",
	},
	{
		id: 4,
		title: "Polaris PUH 4550 WIFI IQ Home Havo namlagichi",
		image: "/products/product-4.png",
		price: 2199000,
		monthlyPrice: 183250,
		monthlyDuration: 18,
		reviewsText: "Sharh yo‘q",
		badge: "Xit savdo",
		discount: "0•0•12",
		discountSecondary: "50•0•2",
	},
	{
		id: 5,
		title: "Resanta YB-2 Havo namlagichi",
		image: "/products/product-5.png",
		price: 359000,
		monthlyPrice: 29917,
		monthlyDuration: 18,
		reviewsText: "Sharh yo‘q",
		badge: "Xit savdo",
		discount: "50•0•2",
	},
];
