export const regionOptions = {
	"Toshkent shahri": [
		"Bektemir",
		"Chilonzor",
		"Mirobod",
		"Mirzo Ulug'bek",
		"Olmazor",
		"Sergeli",
		"Shayxontohur",
		"Uchtepa",
		"Yakkasaroy",
		"Yashnobod",
		"Yunusobod",
		"Yangihayot",
	],
	Andijon: [
		"Andijon shahri",
		"Andijon tumani",
		"Asaka",
		"Baliqchi",
		"Bo'ston",
		"Buloqboshi",
		"Jalaquduq",
		"Izboskan",
		"Xo'jaobod",
		"Marhamat",
		"Oltinko'l",
		"Paxtaobod",
		"Qo'rg'ontepa",
		"Shahrixon",
		"Ulug'nor",
		"Xonobod",
	],
	Buxoro: [
		"Buxoro shahri",
		"Buxoro tumani",
		"G'ijduvon",
		"Jondor",
		"Kogon shahri",
		"Kogon tumani",
		"Olot",
		"Peshku",
		"Qorako'l",
		"Qorovulbozor",
		"Romitan",
		"Shofirkon",
		"Vobkent",
	],
	Fargona: [
		"Farg'ona shahri",
		"Bag'dod",
		"Beshariq",
		"Buvayda",
		"Dang'ara",
		"Farg'ona tumani",
		"Furqat",
		"Oltiariq",
		"Qo'qon",
		"Quva",
		"Quvasoy",
		"Rishton",
		"So'x",
		"Toshloq",
		"Uchko'prik",
		"O'zbekiston",
		"Yozyovon",
		"Marg'ilon",
	],
	Jizzax: [
		"Jizzax shahri",
		"Arnasoy",
		"Baxmal",
		"Do'stlik",
		"Forish",
		"G'allaorol",
		"Mirzacho'l",
		"Paxtakor",
		"Yangiobod",
		"Zafarobod",
		"Zarbdor",
		"Zomin",
		"Sharof Rashidov",
	],
	Qashqadaryo: [
		"Qarshi shahri",
		"Chiroqchi",
		"Dehqonobod",
		"G'uzor",
		"Kasbi",
		"Kitob",
		"Koson",
		"Ko'kdala",
		"Mirishkor",
		"Muborak",
		"Nishon",
		"Qamashi",
		"Qarshi tumani",
		"Shahrisabz",
		"Yakkabog'",
	],
	Navoiy: [
		"Navoiy shahri",
		"Zarafshon",
		"Gozg'on",
		"Karmana",
		"Konimex",
		"Navbahor",
		"Nurota",
		"Qiziltepa",
		"Tomdi",
		"Uchquduq",
		"Xatirchi",
	],
	Namangan: [
		"Namangan shahri",
		"Chortoq",
		"Chust",
		"Kosonsoy",
		"Mingbuloq",
		"Namangan tumani",
		"Norin",
		"Pop",
		"To'raqo'rg'on",
		"Uchqo'rg'on",
		"Uychi",
		"Yangiqo'rg'on",
	],
	Samarqand: [
		"Samarqand shahri",
		"Bulung'ur",
		"Ishtixon",
		"Jomboy",
		"Kattaqo'rg'on shahri",
		"Kattaqo'rg'on tumani",
		"Narpay",
		"Nurobod",
		"Oqdaryo",
		"Paxtachi",
		"Pastdarg'om",
		"Payariq",
		"Qo'shrabot",
		"Samarqand tumani",
		"Tayloq",
		"Urgut",
	],
	Sirdaryo: [
		"Guliston shahri",
		"Boyovut",
		"Guliston tumani",
		"Mirzaobod",
		"Oqoltin",
		"Sardoba",
		"Sayxunobod",
		"Sirdaryo tumani",
		"Shirin",
		"Xovos",
		"Yangiyer",
	],
	Surxondaryo: [
		"Termiz shahri",
		"Angor",
		"Bandixon",
		"Boysun",
		"Denov",
		"Jarqo'rg'on",
		"Muzrabot",
		"Oltinsoy",
		"Sariosiyo",
		"Sherobod",
		"Sho'rchi",
		"Termiz tumani",
		"Qiziriq",
		"Qumqo'rg'on",
		"Uzun",
	],
	Toshkent: [
		"Angren",
		"Bekobod shahri",
		"Bekobod tumani",
		"Bo'ka",
		"Bo'stonliq",
		"Chinoz",
		"Olmaliq",
		"Ohangaron shahri",
		"Ohangaron tumani",
		"Oqqo'rg'on",
		"Parkent",
		"Piskent",
		"Quyichirchiq",
		"Yangiyo'l shahri",
		"Yangiyo'l tumani",
		"Yuqorichirchiq",
		"Zangiota",
		"O'rtachirchiq",
		"Qibray",
		"Chirchiq",
		"Nurafshon",
	],
	Xorazm: [
		"Urganch shahri",
		"Bog'ot",
		"Gurlan",
		"Hazorasp",
		"Xiva shahri",
		"Xiva tumani",
		"Qo'shko'pir",
		"Shovot",
		"Urganch tumani",
		"Xonqa",
		"Yangiariq",
		"Yangibozor",
		"Tuproqqal'a",
	],
	"Qoraqalpog'iston Respublikasi": [
		"Nukus shahri",
		"Amudaryo",
		"Beruniy",
		"Bo'zatov",
		"Chimboy",
		"Ellikqal'a",
		"Kegeyli",
		"Mo'ynoq",
		"Nukus tumani",
		"Qanliko'l",
		"Qo'ng'irot",
		"Qorao'zak",
		"Shumanay",
		"Taxtako'pir",
		"To'rtko'l",
		"Xo'jayli",
		"Taxiatosh",
	],
} as const;

export type RegionOptionKey = keyof typeof regionOptions;
